### ISSUE TITLE
Kode terdapat error saat mengambil Library

### ISSUE THREAD

**Issue by Muhammad-Ikhwan-Fathulloh** [MuadzAlch/UTS_WEB2#1]
Fatal error
: Uncaught Error: The script tried to call a method on an incomplete object. Please ensure that the class definition "Library" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in C:\laragon\www\Ngajar-UTB\Web2-2023-2024-Genap\221PA\UTS_WEB2\index.php:280 Stack trace: #0 {main} thrown in
C:\laragon\www\Ngajar-UTB\Web2-2023-2024-Genap\221PA\UTS_WEB2\index.php
on line
280

![image](https://github.com/MuadzAlch/UTS_WEB2/assets/77288014/f13b2d32-7894-4f43-a24c-b7eb41508943)

**Comment by MuadzAlch** [comment]
![Screenshot 2024-05-02 235240](https://github.com/MuadzAlch/UTS_WEB2/assets/149521155/2610d1f7-9043-4515-8445-30de855ee2da)

tapi di saya bisa pak
